### ISSUE TITLE
"Invalid request. 'sha' wasn't supplied" error on image upload

### ISSUE THREAD

**Issue by oscarmorrison** [ifvictr/ghost-storage-github#18] opened 2019-05-20 08:04 UTC
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1651212/58005712-9c706d00-7b29-11e9-8258-0a19e13a29f9.png">

```
NAME: InternalServerError
CODE: 422
MESSAGE: {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}
```

**Comment by ifvictr** [comment] 2019-05-21 00:10
Hi @oscarmorrison!

Thanks for reporting this. Could you let me know which version of ghost-github you were using, and the action you were performing (uploading or replacing an image)?

**Comment by oscarmorrison** [comment] 2019-05-21 00:13
Thanks for the quick response @ifvictr 

on the latest version of `ghost-github` 1.0.2

![image](https://user-images.githubusercontent.com/1651212/58059584-eea8a100-7bb0-11e9-9a5a-05b7ecdf359b.png)

And on ghost v2.22.1 (upgraded yesterday)

That error is when I am just trying to upload a new image into a post. The images actually do upload: https://github.com/oscarmorrison/blog.oscarmorrison.com-assets/tree/master/2019/05 but somehow not correctly telling ghost about the image

**Comment by ifvictr** [comment] 2019-05-22 07:41
Did the error also occur before you upgraded to v2.22.1? If not, what was the version you upgraded from?

**Comment by oscarmorrison** [comment] 2019-05-22 10:47
Hmm. I am not 100% sure. I hadn't added a post for a while, I upgraded without checking. 
I was on v2.0 before.

**Comment by ifvictr** [comment] 2019-05-23 19:53
Hmm, okay. How did you set up the adapter? Could I see your config file?

**Comment by ifvictr** [comment] 2019-05-26 01:50
@oscarmorrison I just tested `ghost-github@1.0.2` on `ghost@2.22.3` locally, and couldn't reproduce the error you were getting. I think probably didn't configure it correctly—could I see how your config looks like?

**Comment by oscarmorrison** [comment] 2019-05-26 01:53
`/var/www/ghost# cat config.production.json`

<img width="507" alt="Screen Shot 2019-05-26 at 11 52 32 am" src="https://user-images.githubusercontent.com/1651212/58376351-c94ed500-7fac-11e9-92aa-4229ebf3f8b6.png">

**Comment by ifvictr** [comment] 2019-05-26 05:32
I just tested a bit more and was finally able to reproduce your error, while also uncovering a few others! I'll start looking into how to fix all of them and will try to ship an update by the end of next week. Stay tuned!

**Comment by oscarmorrison** [comment] 2019-05-27 01:10
Thanks @ifvictr

**Comment by oscarmorrison** [comment] 2019-06-21 04:27
@ifvictr any update? Thanks

**Comment by ifvictr** [comment] 2019-09-11 02:15
@oscarmorrison Sorry, haven't had time to delve deeper into this issue. I'll post an update when I find the issue :)

**Comment by ifvictr** [comment] 2020-03-24 04:46
@oscarmorrison Looks like this was happening because the adapter was trying to update an existing file with the contents of the uploaded file, which was caused by [`GitHubStorage#exists`](https://github.com/ifvictr/ghost-storage-github/blob/v1.0.2/index.js#L23). I'm about to release 2.0.0, it should be fixed there!

**Closed as completed by ifvictr** 2020-03-24 04:46 UTC
Labels: bug, help wanted

**Comment by ifvictr** [comment] 2020-03-28 08:59
Update: It's here! Enjoy: https://github.com/ifvictr/ghost-storage-github/releases/tag/v2.0.1
